package server

import (
	pb "afsfs/generated/afs"
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sync"
	"sync/atomic"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// FileHandle represent one open file on the server side
type FileHandle struct {
	path    string
	isWrite bool
}

type dedupEntry struct {
	response interface{}
}

// Handler implements the AFSServiceServer interface generated by protoc
type Handler struct {
	pb.UnimplementedAFSServiceServer

	inputDir  string // where the input file text live
	outputDir string // where output files live

	// handle table: HandleID -> FileHandle
	handleMu sync.Mutex
	handles  map[int64]*FileHandle

	// version table: filepath -> version number
	versionMu sync.Mutex
	versions  map[string]int64

	// atomic counter for generating unique handle IDs
	nextHandle atomic.Int64

	dedupMu    sync.Mutex
	dedupTable map[string]dedupEntry // key = clientID:reqSeq

	serverID   string
	serverAddr string

	primaryMu        sync.RWMutex
	primary          bool
	knownPrimaryAddr string // last known primary address (used by GetPrimary on backups)

	peers   []*peerClient
	peersMu sync.RWMutex

	lastHeartbeat   time.Time
	lastHeartbeatMu sync.Mutex

	// senderRunning prevents launching duplicate heartbeat sender goroutines
	// if promoteToPrimary is called more than once (concurrent elections).
	senderRunning atomic.Bool
}

func NewHandler(
	inputDir string,
	outputDir string,
	serverID string,
	serverAddr string,
	peerInfos []PeerInfo,
	isPrimary bool,
) (*Handler, error) {
	h := &Handler{
		inputDir:      inputDir,
		outputDir:     outputDir,
		handles:       make(map[int64]*FileHandle),
		versions:      make(map[string]int64),
		dedupTable:    make(map[string]dedupEntry),
		serverID:      serverID,
		serverAddr:    serverAddr,
		primary:       isPrimary,
		lastHeartbeat: time.Now(),
	}
	if isPrimary {
		h.knownPrimaryAddr = serverAddr
	}

	for _, p := range peerInfos {
		peer, err := newPeerClient(p.ID, p.Addr)
		if err != nil {
			log.Printf("warning: could not connect to peer %s at %s: %v",
				p.ID, p.Addr, err)
			continue
		}
		h.peers = append(h.peers, peer)
	}

	if err := h.initVersion(inputDir); err != nil {
		return nil, fmt.Errorf("scanning input dir: %w", err)
	}
	if err := h.initVersion(outputDir); err != nil {
		return nil, fmt.Errorf("scanning output dir: %w", err)
	}

	if isPrimary {
		h.startHeartbeatSender()
	} else {
		h.startHeartbeatMonitor()
		// Sync from primary in background — retries for ~60s to handle
		// startup races (this server may start before the primary is ready).
		go h.syncFromPrimaryWithRetry()
	}

	return h, nil
}

// dialPeer opens a raw one-shot gRPC connection to addr.
func dialPeer(addr string) (*grpc.ClientConn, error) {
	return grpc.NewClient(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
}

// syncFromPrimaryWithRetry retries sync until it succeeds (up to ~60s).
// Works both at startup and when called from AnnouncePrimary after recovery.
func (h *Handler) syncFromPrimaryWithRetry() {
	for i := 0; i < 30; i++ {
		if i > 0 {
			time.Sleep(2 * time.Second)
		}

		// Step 1: find who the primary is
		primaryAddr := h.resolvePrimaryAddr()
		if primaryAddr == "" {
			log.Printf("server %s: cannot find primary yet (attempt %d)", h.serverID, i+1)
			continue
		}

		// Don't sync from ourselves.
		if primaryAddr == h.serverAddr {
			log.Printf("server %s: I am the primary, no sync needed", h.serverID)
			return
		}

		// Step 2: get an AFSServiceClient for the primary.
		// Prefer an existing peer connection; fall back to a raw dial.
		var stub pb.AFSServiceClient
		var rawConn *grpc.ClientConn

		for _, peer := range h.copyPeers() {
			if peer.addr == primaryAddr {
				stub = peer.stub
				break
			}
		}
		if stub == nil {
			conn, err := dialPeer(primaryAddr)
			if err != nil {
				log.Printf("server %s: cannot dial primary %s: %v", h.serverID, primaryAddr, err)
				continue
			}
			rawConn = conn
			stub = pb.NewAFSServiceClient(conn)
		}

		// Step 3: call SyncState
		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		resp, err := stub.SyncState(ctx, &pb.SyncStateRequest{ServerId: h.serverID})
		cancel()
		if rawConn != nil {
			rawConn.Close()
		}
		if err != nil {
			log.Printf("server %s: SyncState from %s failed: %v", h.serverID, primaryAddr, err)
			continue
		}

		// Step 4: apply files that are missing or stale
		synced := 0
		for _, entry := range resp.Files {
			fullPath := filepath.Join(h.outputDir, filepath.Base(entry.Path))
			h.versionMu.Lock()
			currentVersion, exists := h.versions[fullPath]
			h.versionMu.Unlock()

			if !exists || entry.Version > currentVersion {
				if err := os.WriteFile(fullPath, entry.Data, 0644); err != nil {
					log.Printf("server %s: failed to write synced file %s: %v",
						h.serverID, fullPath, err)
					continue
				}
				h.versionMu.Lock()
				h.versions[fullPath] = entry.Version
				h.versionMu.Unlock()
				log.Printf("server %s: synced %s (version %d)", h.serverID, entry.Path, entry.Version)
				synced++
			}
		}
		log.Printf("server %s synced %d files from primary %s", h.serverID, synced, primaryAddr)
		return
	}
	log.Printf("server %s: could not sync from primary — starting fresh", h.serverID)
}

// resolvePrimaryAddr asks peers who the primary is.
func (h *Handler) resolvePrimaryAddr() string {
	// First check our own knownPrimaryAddr
	h.primaryMu.RLock()
	known := h.knownPrimaryAddr
	h.primaryMu.RUnlock()
	if known != "" && known != h.serverAddr {
		return known
	}

	for _, peer := range h.copyPeers() {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
		resp, err := peer.stub.GetPrimary(ctx, &pb.GetPrimaryRequest{})
		cancel()
		if err == nil && resp.PrimaryAddr != "" {
			return resp.PrimaryAddr
		}
	}
	return ""
}

func (h *Handler) initVersion(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return os.MkdirAll(dir, 0755)
		}
		return err
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			fullPath := filepath.Join(dir, entry.Name())
			h.versions[fullPath] = 1
		}
	}
	return nil
}

func (h *Handler) Open(ctx context.Context, req *pb.OpenRequest) (*pb.OpenResponse, error) {
	key := dedupKey(req.ClientId, req.ReqSeq)
	h.dedupMu.Lock()
	if entry, exists := h.dedupTable[key]; exists {
		h.dedupMu.Unlock()
		return entry.response.(*pb.OpenResponse), nil
	}
	h.dedupMu.Unlock()

	fullPath, err := h.resolvePath(req.Path)
	if err != nil {
		return &pb.OpenResponse{Error: err.Error()}, nil
	}

	if _, err := os.Stat(fullPath); os.IsNotExist(err) {
		return &pb.OpenResponse{Error: fmt.Sprintf("file not found: %s", req.Path)}, nil
	}

	id := h.nextHandle.Add(1)

	h.handleMu.Lock()
	h.handles[id] = &FileHandle{path: fullPath, isWrite: req.Write}
	h.handleMu.Unlock()

	resp := &pb.OpenResponse{FileHandleId: id}

	h.dedupMu.Lock()
	h.dedupTable[key] = dedupEntry{response: resp}
	h.dedupMu.Unlock()

	return resp, nil
}

func (h *Handler) FetchFile(ctx context.Context, req *pb.FetchFileRequest) (*pb.FetchFileResponse, error) {
	fullPath, err := h.resolvePath(req.Path)
	if err != nil {
		return &pb.FetchFileResponse{Error: err.Error()}, nil
	}

	data, err := os.ReadFile(fullPath)
	if err != nil {
		return &pb.FetchFileResponse{
			Error: fmt.Sprintf("reading file: %v", err),
		}, nil
	}

	h.versionMu.Lock()
	version := h.versions[fullPath]
	h.versionMu.Unlock()

	return &pb.FetchFileResponse{
		Data:    data,
		Version: version,
	}, nil
}

func (h *Handler) TestAuth(ctx context.Context, req *pb.TestAuthRequest) (*pb.TestAuthResponse, error) {
	fullPath, err := h.resolvePath(req.Path)
	if err != nil {
		return &pb.TestAuthResponse{IsValid: false}, nil
	}

	h.versionMu.Lock()
	currentVersion := h.versions[fullPath]
	h.versionMu.Unlock()

	return &pb.TestAuthResponse{
		IsValid: currentVersion == req.CachedVersion,
		Version: currentVersion,
	}, nil
}

func (h *Handler) StoreFile(ctx context.Context, req *pb.StoreFileRequest) (*pb.StoreFileResponse, error) {
	// Only primary accepts writes
	if !h.isPrimary() {
		return &pb.StoreFileResponse{
			Error: "not primary: send writes to primary",
		}, nil
	}

	key := dedupKey(req.ClientId, req.ReqSeq)
	h.dedupMu.Lock()
	if entry, exists := h.dedupTable[key]; exists {
		h.dedupMu.Unlock()
		return entry.response.(*pb.StoreFileResponse), nil
	}
	h.dedupMu.Unlock()

	fullPath := filepath.Join(h.outputDir, filepath.Base(req.Path))
	tmpPath := fullPath + ".tmp"

	if err := os.WriteFile(tmpPath, req.Data, 0644); err != nil {
		return &pb.StoreFileResponse{
			Error: fmt.Sprintf("writing file: %v", err),
		}, nil
	}

	if err := os.Rename(tmpPath, fullPath); err != nil {
		return &pb.StoreFileResponse{
			Error: fmt.Sprintf("renaming file: %v", err),
		}, nil
	}

	h.versionMu.Lock()
	h.versions[fullPath]++
	newVersion := h.versions[fullPath]
	h.versionMu.Unlock()

	// Replicate to all backups (best-effort)
	h.replicateToAll("store", req.Path, req.Data, newVersion)

	resp := &pb.StoreFileResponse{Version: newVersion}

	h.dedupMu.Lock()
	h.dedupTable[key] = dedupEntry{response: resp}
	h.dedupMu.Unlock()

	return resp, nil
}

func (h *Handler) CreateFile(ctx context.Context, req *pb.CreateFileRequest) (*pb.CreateFileResponse, error) {
	// Only primary accepts mutations
	if !h.isPrimary() {
		return &pb.CreateFileResponse{
			Error: "not primary: send writes to primary",
		}, nil
	}

	key := dedupKey(req.ClientId, req.ReqSeq)
	h.dedupMu.Lock()
	if entry, exists := h.dedupTable[key]; exists {
		h.dedupMu.Unlock()
		return entry.response.(*pb.CreateFileResponse), nil
	}
	h.dedupMu.Unlock()

	fullPath := filepath.Join(h.outputDir, filepath.Base(req.Path))

	if _, err := os.Stat(fullPath); err == nil {
		return &pb.CreateFileResponse{
			Error: fmt.Sprintf("file already exists: %s", req.Path),
		}, nil
	}

	fd, err := os.Create(fullPath)
	if err != nil {
		return &pb.CreateFileResponse{
			Error: fmt.Sprintf("creating file: %v", err),
		}, nil
	}
	fd.Close()

	h.versionMu.Lock()
	h.versions[fullPath] = 1
	h.versionMu.Unlock()

	id := h.nextHandle.Add(1)
	h.handleMu.Lock()
	h.handles[id] = &FileHandle{path: fullPath, isWrite: true}
	h.handleMu.Unlock()

	// Replicate create to all backups
	h.replicateToAll("create", req.Path, []byte{}, 1)

	resp := &pb.CreateFileResponse{FileHandleId: id}

	h.dedupMu.Lock()
	h.dedupTable[key] = dedupEntry{response: resp}
	h.dedupMu.Unlock()

	return resp, nil
}

func (h *Handler) DeleteFile(ctx context.Context, req *pb.DeleteFileRequest) (*pb.DeleteFileResponse, error) {
	// Only primary accepts mutations
	if !h.isPrimary() {
		return &pb.DeleteFileResponse{
			Error: "not primary: send writes to primary",
		}, nil
	}

	key := dedupKey(req.ClientId, req.ReqSeq)
	h.dedupMu.Lock()
	if entry, exists := h.dedupTable[key]; exists {
		h.dedupMu.Unlock()
		return entry.response.(*pb.DeleteFileResponse), nil
	}
	h.dedupMu.Unlock()

	fullPath := filepath.Join(h.outputDir, filepath.Base(req.Path))

	if err := os.Remove(fullPath); err != nil && !os.IsNotExist(err) {
		return &pb.DeleteFileResponse{
			Error: fmt.Sprintf("deleting file: %v", err),
		}, nil
	}

	h.versionMu.Lock()
	delete(h.versions, fullPath)
	h.versionMu.Unlock()

	// Replicate delete to all backups
	h.replicateToAll("delete", req.Path, []byte{}, 0)

	resp := &pb.DeleteFileResponse{}

	h.dedupMu.Lock()
	h.dedupTable[key] = dedupEntry{response: resp}
	h.dedupMu.Unlock()

	return resp, nil
}

func (h *Handler) CloseFile(ctx context.Context, req *pb.CloseFileRequest) (*pb.CloseFileResponse, error) {
	h.handleMu.Lock()
	_, exists := h.handles[req.FileHandleId]
	if exists {
		delete(h.handles, req.FileHandleId)
	}
	h.handleMu.Unlock()

	if !exists {
		return &pb.CloseFileResponse{
			Error: fmt.Sprintf("unknown handle: %d", req.FileHandleId),
		}, nil
	}

	return &pb.CloseFileResponse{}, nil
}

// resolvePath takes a file name and returns the absolute path by checking which directory contains it.
func (h *Handler) resolvePath(name string) (string, error) {
	base := filepath.Base(name)

	if base == "." || base == ".." {
		return "", fmt.Errorf("invalid path %s", name)
	}

	inputPath := filepath.Join(h.inputDir, base)
	if _, err := os.Stat(inputPath); err == nil {
		return inputPath, nil
	}

	outputPath := filepath.Join(h.outputDir, base)
	if _, err := os.Stat(outputPath); err == nil {
		return outputPath, nil
	}

	// Not found in any directory — return inputPath so caller can report error
	return inputPath, nil
}

// Replicate RPC handler — called on BACKUPS by the primary
func (h *Handler) Replicate(ctx context.Context, req *pb.ReplicateRequest) (*pb.ReplicateResponse, error) {
	switch req.Operation {
	case "store":
		fullPath := filepath.Join(h.outputDir, filepath.Base(req.Path))
		tmpPath := fullPath + ".tmp"
		if err := os.WriteFile(tmpPath, req.Data, 0644); err != nil {
			return &pb.ReplicateResponse{
				Error: fmt.Sprintf("writing: %v", err),
			}, nil
		}
		os.Rename(tmpPath, fullPath)
		h.versionMu.Lock()
		h.versions[fullPath] = req.Version
		h.versionMu.Unlock()

	case "create":
		fullPath := filepath.Join(h.outputDir, filepath.Base(req.Path))
		os.WriteFile(fullPath, []byte{}, 0644)
		h.versionMu.Lock()
		h.versions[fullPath] = req.Version
		h.versionMu.Unlock()

	case "delete":
		fullPath := filepath.Join(h.outputDir, filepath.Base(req.Path))
		os.Remove(fullPath)
		h.versionMu.Lock()
		delete(h.versions, fullPath)
		h.versionMu.Unlock()
	}

	return &pb.ReplicateResponse{}, nil
}

// collectFilesForSync reads all files in a directory for SyncState
func (h *Handler) collectFilesForSync(dir string) ([]*pb.SyncFileEntry, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var result []*pb.SyncFileEntry
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		fullPath := filepath.Join(dir, entry.Name())
		data, err := os.ReadFile(fullPath)
		if err != nil {
			continue
		}
		h.versionMu.Lock()
		version := h.versions[fullPath]
		h.versionMu.Unlock()

		result = append(result, &pb.SyncFileEntry{
			Path:    entry.Name(),
			Data:    data,
			Version: version,
		})
	}
	return result, nil
}

func dedupKey(clientID string, reqSeq int64) string {
	return fmt.Sprintf("%s:%d", clientID, reqSeq)
}
